# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: weekly
  ignore:
      - dependency-name: "Microsoft.CodeAnalysis.Common"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Features"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
      - dependency-name: "Microsoft.CodeAnalysis.VisualBasic"
      - dependency-name: "Microsoft.Bcl.AsyncInterfaces"
      - dependency-name: "Microsoft.Bcl.HashCode"