variables:
- group: Sleet
- name: Configuration
  value: Release
- name: DOTNET_NOLOGO
  value: 'true'

trigger:
  paths:
    exclude:
    - docs/*
    - README.md

stages:

- stage: build
  jobs:
  - job: build
    strategy:
      matrix:
        # ubuntu-latest:
        #  vm: ubuntu-latest
        #macOS-latest:
        #  vm: macOS-latest
        windows-latest:
          vm: windows-latest
    pool:
      vmImage: $(vm)
    steps:
    - checkout: self
      clean: 'true'

    - task: UseDotNet@2
      inputs:
        version: 5.0.100-rc.2.20479.15
        performMultiLevelLookup: true

    - task: UseDotNet@2
      inputs:
        version: 2.1.x
        performMultiLevelLookup: true

    - bash: dotnet msbuild -r -m:1 -p:versionsuffix="$BUILD_SOURCEBRANCHNAME.$BUILD_BUILDID"
      displayName: build

    - task: VSTest@2
      displayName: Test
      inputs:
        testAssemblyVer2: '**/bin/**/*Tests.dll'
        runInParallel: true
        codeCoverageEnabled: false
        publishRunAttachments: true
        diagnosticsEnabled: false
        rerunFailedTests: true

    - bash: |
        dotnet tool install -g --version 2.3.33 sleet
        sleet push bin --config none -f --verbose -p "SLEET_FEED_CONTAINER=nuget" -p "SLEET_FEED_CONNECTIONSTRING=$(SLEET_FEED_CONNECTIONSTRING)" -p "SLEET_FEED_TYPE=azure"
      displayName: sleet
      condition: eq(variables['vm'], 'windows-latest')

    - publish: '$(Pipeline.Workspace)/s/bin'
      artifact: 'bin'

  - job: test
    strategy:
      matrix:
        ubuntu-latest:
          vm: ubuntu-latest
        macOS-latest:
          vm: macOS-latest
        windows-latest:
          vm: windows-latest
    dependsOn: build
    pool:
      vmImage: $(vm)
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        version: 5.0.100-rc.2.20479.15
        performMultiLevelLookup: true

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: bin
        path: '$(Pipeline.Workspace)/s/bin'

    - bash: dotnet test -p:versionsuffix="$BUILD_SOURCEBRANCHNAME.$BUILD_BUILDID"
      workingDirectory: src/Acceptance
      displayName: test