namespace Avatars
{
    static class Constants
    {
        public const string AutoGenerated = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Avatar v" + ThisAssembly.Project.Version + " (" + ThisAssembly.Project.RepositorySha + @").
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";
    }
}
