// <auto-generated>
//     This code was included from Avatar.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Avatars
{
    partial class Avatar
    {
        static Avatar()
        {
            AvatarFactory.Default = new StaticAvatarFactory();
            OnInitialized();
        }

        /// <summary>
        /// Invoked after the default <see cref="AvatarFactory.Default"/> 
        /// is initialized.
        /// </summary>
        static partial void OnInitialized();
    }
}
