//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stunts.CodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stunts.CodeAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a base type is specified, it must be the first type in the type arguments list..
        /// </summary>
        internal static string BaseTypeNotFirst_Description {
            get {
                return ResourceManager.GetString("BaseTypeNotFirst_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base type &apos;{0}&apos; must be the first in the type arguments list..
        /// </summary>
        internal static string BaseTypeNotFirst_Message {
            get {
                return ResourceManager.GetString("BaseTypeNotFirst_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base type must be first.
        /// </summary>
        internal static string BaseTypeNotFirst_Title {
            get {
                return ResourceManager.GetString("BaseTypeNotFirst_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify more than one base type..
        /// </summary>
        internal static string DuplicateBaseType_Description {
            get {
                return ResourceManager.GetString("DuplicateBaseType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify more than one base type..
        /// </summary>
        internal static string DuplicateBaseType_Message {
            get {
                return ResourceManager.GetString("DuplicateBaseType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple base types specified.
        /// </summary>
        internal static string DuplicateBaseType_Title {
            get {
                return ResourceManager.GetString("DuplicateBaseType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot intercept sealed types..
        /// </summary>
        internal static string InvalidSealedBaseType {
            get {
                return ResourceManager.GetString("InvalidSealedBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only classes and interfaces can be used in stunts. Invalid set of symbols: {0}..
        /// </summary>
        internal static string InvalidStuntTypes {
            get {
                return ResourceManager.GetString("InvalidStuntTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested types are not supported yet..
        /// </summary>
        internal static string NestedType_Description {
            get {
                return ResourceManager.GetString("NestedType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate code for nested types yet: {0}.
        /// </summary>
        internal static string NestedType_Message {
            get {
                return ResourceManager.GetString("NestedType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested types not supported.
        /// </summary>
        internal static string NestedType_Title {
            get {
                return ResourceManager.GetString("NestedType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify sealed base type..
        /// </summary>
        internal static string SealedBaseType_Description {
            get {
                return ResourceManager.GetString("SealedBaseType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify sealed base type &apos;{0}&apos;...
        /// </summary>
        internal static string SealedBaseType_Message {
            get {
                return ResourceManager.GetString("SealedBaseType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sealed base type.
        /// </summary>
        internal static string SealedBaseType_Title {
            get {
                return ResourceManager.GetString("SealedBaseType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one symbol is required..
        /// </summary>
        internal static string SymbolRequired {
            get {
                return ResourceManager.GetString("SymbolRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one base class can be specified, and it must be the first in the type list. Invalid set of symbols: {0}..
        /// </summary>
        internal static string WrongBaseType {
            get {
                return ResourceManager.GetString("WrongBaseType", resourceCulture);
            }
        }
    }
}
