name: release
on:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true
  Configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
      - name: ⚙ dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: 🙏 build
        run: dotnet msbuild -r -m:1 -bl:build.binlog -p:version=${GITHUB_REF#refs/*/v}
      - name: 🧪 test net5.0
        run: dotnet test --no-build -f net5.0 -m:1
        working-directory: src/Avatar.UnitTests
      - name: 📦 pack
        run: dotnet msbuild -t:pack -m:1 -bl:pack.binlog -p:version=${GITHUB_REF#refs/*/v}
        working-directory: src/Pack
      - name: 🔼 logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: '**/*.binlog'
      - name: 🚀 nuget
        run: rm ./bin/ManualAvatars*.nupkg && dotnet nuget push ./bin/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate