# Runs on new issues/PRs and applies sponsor labels

name: sponsors
on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  sponsors:
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2

      - name: 🔽 gh 
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install gh

      - name: 💛 sponsors
        run: ./.github/workflows/sponsors.ps1
        env:
          GH_TOKEN: ${{ secrets.DEVLOOPED_TOKEN }}
